const randomTextFromArray = (texts: string[]): string => {
  return texts[Math.floor(Math.random() * texts.length)];
};

const randomText = (name: string): string => {
  const morningOnlyTexts = [
    `Good morning, ${name} ☀️`,
    `Top of the morning to you, ${name}! 🥐`,
    `Rise and shine, ${name} 🌅`,
    `Hope you slept well, ${name} 😴`,
    `Morning, ${name}. Ready to take on the day? 💪`,
    `Hey ${name}, coffee's brewing! ☕️`,
    `Rise and grind, ${name} 🏋️‍♂️`,
    `New day, new opportunities, ${name} 🌄`,
    `The early bird gets the worm, ${name} 🐦`,
    `Boot sequence complete, ${name}. Let’s launch 🚀`,
    `Up and at 'em, ${name}! 🐓`,
    `Let’s make today awesome, ${name} 💫`,
    `First light and first coffee, right ${name}? ☕️`,
    `It’s go time, ${name} 🔥`,
    `Sun’s out, ambition’s up, ${name} 😎`,
    `Time to shine, ${name} ✨`,
    `New day, new tasks — let’s crush them, ${name} ✅`,
    `Hello sunshine! ${name}, you’re glowing today ☀️`,
    `Mission log: ${name} is online and operational 🛰️`,
    `Don't just wake up, show up — let’s go ${name} 💼`,
    `System check: ${name} is 100% charged ⚡️`,
    `Fuel up and fly high today, ${name} ✈️`,
    `The world is waiting for you, ${name} 🌍`,
    `Morning vibes are elite today, right ${name}? 💎`,
    `Ready to make some waves, ${name}? 🌊`,
    `Fresh start, fresh goals, ${name} 🍃`,
    `Sending high-productivity signals your way, ${name} 📡`,
    `Make it count today, ${name} 🎯`,
    `Good morning, Captain ${name}. Engines are idling 🏎️`,
    `Early start? That’s the spirit, ${name} 🏆`,
    `Morning, ${name}! Let's turn caffeine into code ☕️💻`,
    `Dawn patrol is active. Welcome back, ${name} 🦅`,
    `The horizon looks promising today, ${name} 🔭`,
    `A brand new chapter starts now, ${name} 📖`,
    `Let's get those wins early, ${name} 🏅`,
    `The solar panels are out and soaking it up, ${name} 🔋`,
    `Morning, ${name}! Your potential is infinite ♾️`,
    `Sunlight looks good on your workspace, ${name} 🪴`,
    `Ready for lift-off, ${name}? 🛫`,
    `Go get 'em, tiger! ${name} 🐯`,
    `Another chance to be great, ${name} 🌟`,
    `The morning air is crisp, let's work, ${name} ❄️`,
    `Eyes on the prize today, ${name} 👁️‍🗨️`,
    `A quick stretch and then we go, ${name} 🧘‍♂️`,
    `Morning, ${name}! Stay focused and stay awesome 🧊`,
  ];

  const afternoonOnlyTexts = [
    `Good afternoon, ${name} 🌞`,
    `Hope your day is going well, ${name} 😊`,
    `Hey ${name}, how’s your day so far? 🕑`,
    `You're halfway through, ${name}! 🧭`,
    `Keep up the great work, ${name} 👏`,
    `Hello there, ${name} 👋`,
    `A productive afternoon to you, ${name} 🛠️`,
    `Let’s power through the afternoon, ${name} ⚡️`,
    `Still going strong, ${name}? 🔋`,
    `Orbit stabilizing… productivity at peak, ${name} 🌑`,
    `Need a snack break, ${name}? 🍎`,
    `Still on track, ${name}? You're killing it 🧨`,
    `Let’s turn that to-do list into a done list, ${name} ✅`,
    `You've got this, ${name}. One hour at a time ⏳`,
    `Ping! Just checking in on you, ${name} 🛎️`,
    `Think of this message as your mid-day high-five 🖐️`,
    `Orbit’s still spinning and so are you, ${name} 🌀`,
    `Don't forget to hydrate, ${name} 💧`,
    `Productivity levels: Rising steadily, Captain ${name} 📈`,
    `It’s a good day to get stuff done, ${name} 🧠`,
    `Orbit is running smooth. Thanks for supporting our project, ${name} 🙌`,
    `Post-lunch energy check! How we doing, ${name}? 🥗`,
    `The sun is at its peak, and so are you, ${name} 🔝`,
    `Focus mode engaged. You're doing great, ${name} 🧘`,
    `Nearly at the finish line for today, ${name} 🏁`,
    `Checking the sensors... ${name} is crushing it! 🚀`,
    `Take a deep breath, ${name}. You've got this 💨`,
    `Afternoon slump? Not for ${name}! 💥`,
    `Your progress today is looking sharp, ${name} 📈`,
    `Stay locked in, ${name}. Almost there 🔒`,
    `Afternoon, ${name}! Don't forget to blink 👁️`,
    `The heavy lifting is mostly done, right ${name}? 🏗️`,
    `You're a productivity machine today, ${name} 🦾`,
    `Sun's past the meridian. Keep cruising, ${name} 🏎️`,
    `Steady as she goes, Captain ${name} ⚓️`,
    `Doing okay, ${name}? Remember to stretch those legs 🚶‍♂️`,
    `Halfway to the weekend vibes, ${name} 🍹`,
    `Efficiency check: ${name} is off the charts 📊`,
    `Afternoon, ${name}! The finish line is in sight 🏁`,
    `Stay hydrated and stay brilliant, ${name} 🧊`,
    `You make this look easy, ${name} 😎`,
    `Keep that momentum rolling, ${name} ⚽️`,
    `Afternoon, ${name}! How's the view from the top? 🏔️`,
    `Almost time to clock out? Keep pushing, ${name} 🕒`,
    `Looking good, ${name}. Keep that energy up ⚡️`,
  ];

  const nightOnlyTexts = [
    `Good evening, ${name} 🌙`,
    `Winding down, ${name}? 🛋️`,
    `Hope your day went well, ${name} 🌆`,
    `Relax, you’ve earned it, ${name} 😌`,
    `Evening vibes, ${name} ✨`,
    `Time to slow down and reflect, ${name} 🧘`,
    `The stars are out, ${name} ⭐️`,
    `Great job today, ${name} 🙌`,
    `Sweet dreams in advance, ${name} 😴`,
    `Orbit doesn’t sleep — but you should soon, ${name} 💤`,
    `The night is calm, ${name}. Time to relax 🌌`,
    `Logging off soon, ${name}? You’ve earned it 📴`,
    `Recharge mode: Initiated for ${name} 🔋`,
    `Even stars need rest — so do you, ${name} 🌟`,
    `Thanks for showing up today, ${name} 💙`,
    `Night shift or night chill? You decide, ${name} 🌃`,
    `May your dreams be bug-free, ${name} 🐛💤`,
    `Another day complete. Well played, ${name} 🎮`,
    `Captain ${name}, mission complete for today 🚀`,
    `Sending good energy for tomorrow, ${name} 🔮`,
    `Sunset looks good on you, ${name} 🌇`,
    `Time to trade the screen for some peace, ${name} 🕯️`,
    `Whatever you didn't finish can wait for tomorrow, ${name} 🗓️`,
    `Refining the logs... ${name} had a solid day 📝`,
    `Peace and quiet at last, right ${name}? 🤫`,
    `End of day report: ${name} was legendary 🎖️`,
    `Cozy up and relax, ${name} 🍵`,
    `The moon is out to watch over your rest, ${name} 🎑`,
    `Hard work deserves a hard rest, ${name} 🛌`,
    `Sleep well, ${name}. Tomorrow is a fresh slate 📖`,
    `Evening, ${name}. Time to switch to dark mode 🌑`,
    `Rest is just a tactical pause, ${name} ⏸️`,
    `Dinner time? Enjoy yourself, ${name} 🍲`,
    `Mission accomplished, ${name}. Over and out 📻`,
    `The city lights are glowing for you, ${name} 🏙️`,
    `Downtime is just as important as uptime, ${name} 🛠️`,
    `Great hustle today, ${name}. Proud of you 🤝`,
    `Evening, ${name}. Let your mind wander 💭`,
    `You survived 100% of today. Nice work, ${name} 💯`,
    `Clear skies and calm thoughts, ${name} ☁️`,
    `Final check-in for the day. You good, ${name}? 👋`,
    `Time to decompress, ${name}. Put the phone down 📵`,
    `Evening, ${name}. Your future self thanks you for today 👤`,
    `The day is done. Be at peace, ${name} 🕊️`,
    `Sleepy eyes, ${name}? Catch those Z's soon 🥱`,
  ];

  const lateNightTexts = [
    `Still awake, ${name}? Respect 🌙`,
    `The grind never sleeps — neither do you, huh ${name}? 😅`,
    `Late-night coding or existential scrolling, ${name}? 💻📱`,
    `You, me, and the moon. Let’s vibe, ${name} 🌕`,
    `Insomniacs anonymous: Welcome, ${name} 😴💤`,
    `Hope you're doing okay, ${name}. Remember to rest soon 🫶`,
    `Late shift? Stay sharp, ${name}🦉`,
    `Quiet hours are the best for deep management. Go get ’em, ${name}. ⌨️`,
    `Is that a second wind I see, ${name}? 🌪️`,
    `Burning the midnight oil again, ${name}? 🔥`,
    `The quietest hours are the most creative, right ${name}? 🎨`,
    `Just you and the terminal, ${name}. Let's get it 🖥️`,
    `Don't forget to blink, ${name}! 👁️`,
    `The city is sleeping, but ${name} is building 🏗️`,
    `Ghost mode activated for ${name} 👻`,
    `Almost morning... or just very late night, ${name}? 🕰️`,
    `Deep focus time. I'll stay quiet, ${name} 😶‍🌫️`,
    `You're a night owl through and through, ${name} 🦉`,
    `Late night, high coffee, big dreams, ${name} ☕️✨`,
    `Orbiting while the world sleeps. You're different, ${name} 🌌`,
    `The blue light is strong tonight, ${name} 📱`,
    `Is it late or is it early, ${name}? 🌀`,
    `Silent streets, loud thoughts, ${name} 🌃`,
    `Your dedication is unmatched, ${name} 🎖️`,
    `Rest is coming soon, ${name}. Just hang in there ⚓️`,
    `The 2 AM club has a new member: ${name} 🎟️`,
    `Working in the shadows, ${name}? 👤`,
    `Nighttime is the best time for big ideas, right ${name}? 💡`,
    `Sleepless on the onyx night, ${name}?`
  ];
// updated time logic 
 const hour = new Date().getHours();

  if (hour >= 22 || hour < 4) return randomTextFromArray(lateNightTexts); // Late Night: 10 PM – 3:59 AM (bridges midnight)
  if (hour >= 17) return randomTextFromArray(nightOnlyTexts);            // Evening: 5 PM – 9:59 PM
  if (hour >= 12) return randomTextFromArray(afternoonOnlyTexts);        // Afternoon: 12 PM – 4:59 PM
  return randomTextFromArray(morningOnlyTexts);                          // Morning: 4 AM – 11:59 AM (fallback)
};

export default randomText;